from flask import Blueprint, render_template, request, jsonify, flash, redirect, url_for
from flask_login import login_required, current_user
from models import db, TrainingProject
from github import Github, GithubException
import os

github_bp = Blueprint('github', __name__)

@github_bp.route('/github/connect', methods=['POST'])
@login_required
def connect_github():
    token = request.form.get('github_token')
    if not token:
        flash('GitHub token is required', 'danger')
        return redirect(url_for('dashboard'))

    try:
        g = Github(token)
        user = g.get_user()
        current_user.github_token = token
        db.session.commit()
        flash(f'Connected to GitHub as {user.login}', 'success')
    except GithubException as e:
        flash(f'GitHub error: {e.data.get("message", str(e))}', 'danger')
    return redirect(url_for('dashboard'))

@github_bp.route('/github/upload-project/<int:project_id>', methods=['POST'])
@login_required
def upload_project(project_id):
    project = TrainingProject.query.get_or_404(project_id)
    if project.user_id != current_user.id:
        return jsonify({'error': 'Unauthorized'}), 403

    if not current_user.github_token:
        flash('Please connect your GitHub account first', 'warning')
        return redirect(url_for('dashboard'))

    repo_name = request.form.get('repo_name', f"aiforge-{project.name.lower().replace(' ', '-')}")
    is_private = request.form.get('is_private', 'false') == 'true'
    description = request.form.get('description', project.description or f"AI training project: {project.name}")

    try:
        g = Github(current_user.github_token)
        user = g.get_user()
        repo = user.create_repo(
            name=repo_name,
            description=description,
            private=is_private,
            auto_init=True
        )

        files = {
            "README.md": f"# {project.name}\n\n{project.description}\n\n## Model\n- Type: {project.model_type}\n- Base: {project.base_model}\n- Method: {project.training_method}",
            "train.py": f"# Training script for {project.name}\n# Generated by AIForge\n\nimport os\nfrom transformers import AutoModelForCausalLM, AutoTokenizer\n# Add your training logic here\n",
            "requirements.txt": "transformers\ndatasets\naccelerate\npeft\ntrl\n"
        }

        for filename, content in files.items():
            repo.create_file(
                path=filename,
                message=f"Initial commit: {filename}",
                content=content,
                branch="main"
            )

        project.github_repo = repo.html_url
        db.session.commit()
        flash(f'Project uploaded to GitHub: {repo.html_url}', 'success')

    except GithubException as e:
        flash(f'GitHub error: {e.data.get("message", str(e))}', 'danger')

    return redirect(url_for('training.projects'))

@github_bp.route('/github/repos')
@login_required
def list_repos():
    if not current_user.github_token:
        return jsonify({'error': 'GitHub not connected'}), 401

    try:
        g = Github(current_user.github_token)
        user = g.get_user()
        repos = [{'name': repo.name, 'url': repo.html_url, 'private': repo.private} for repo in user.get_repos()]
        return jsonify({'repos': repos})
    except GithubException as e:
        return jsonify({'error': str(e)}), 400
